version: "2"
run:
  timeout: 5m
  tests: true

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - revive
    - gocyclo
    - misspell
    - bodyclose
    - noctx
    - funlen
    - gosec
    - lll
    - testifylint
    - asciicheck
    - copyloopvar
    - dogsled
    - dupl
    - errname
    - errorlint
    - exhaustive
    - goconst
    - gocritic
    - godot
    - makezero
    - nakedret
    - nestif
    - nilerr
    - nilnil
    - nolintlint
    - prealloc
    - predeclared
    - reassign
    - unconvert
    - unparam
    - usestdlibvars
    - whitespace

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
    
