run:
  version: "2.1"
  timeout: 5m
  issues-exit-code: 1
  tests: true

linters:
  disable-all: true
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - gofumpt
    - revive
    - gochecknoinits
    - gocyclo
    - misspell
    - whitespace
    - testifylint
    - bodyclose
    - nilerr
    - noctx
    - prealloc
    - unconvert
    - unparam

linters-settings:
  gofumpt:
    extra-rules: true
  revive:
    ignore-generated-header: true
    severity: warning
    rules:
      - name: blank-imports
      - name: context-keys-type
      - name: dot-imports
      - name: error-return
      - name: error-strings
      - name: error-naming
      - name: exported
      - name: if-return
      - name: increment-decrement
      - name: var-naming
      - name: var-declaration
      - name: package-comments
      - name: range
      - name: receiver-naming
      - name: time-naming
      - name: unexported-return
      - name: indent-error-flow
      - name: errorf
  gocyclo:
    min-complexity: 15
  testifylint:
    enable-all: true

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
  new: false
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - revive
        - noctx
        - testifylint
